services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    image: nodets-template
    restart: always
    ports:
      - "443:443"
    networks: 
      - dbnetwork
    volumes:
      - ./Client:/var/www/node
      - /var/www/node/node_modules

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    image: intellihub-template
    restart: always
    ports: 
      - "3000:3000"
    networks: 
      - dbnetwork 

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "docker"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: "mydb"
    networks: 
      - dbnetwork   

networks:
  dbnetwork:
